title: Mathematics I
description: Houses useful re-usable formulas, which create the base for life management, electrical engineering, medicine, and computer science.
show_downloads: true
google_analytics: true
theme: jekyll-theme-slate
markdown: kramdown
avatar: https://user-images.githubusercontent.com/60224159/178119492-91d3cc70-a88f-4b9a-94a0-ca7b68b1d861.png
