title: Mathematics I
description: Houses useful re-usable formulas, which create the base for life management, electrical engineering, medicine, and computer science.
show_downloads: false
google_analytics: false
theme: jekyll-theme-slate
markdown: kramdown
